---
title: "DDS Case Study 2 Codebook"
author: "Brock Friedrich, Quinton Nixon, Peter Flaming, Matthew Trevathan"
date: "August 4, 2018"
output: html_document
---

## Codebook for Fracking Data

This codebook is for the fracking data obtained on http://fracfocus.org/data-download. This includes regulatory data that reports chemicals and proppants used for hydraulic fracturing. The first of two raw datasets consist of deo_well_data.csv (Driftwood), which provides various wells with data such as their identification number and production dates. The second set is fracfocus_registry.csv, which has much more detailed analysis of fracturing operations, their locations, names and the materials and chemicals used in their operation. 

# Driftwood Data Points
 
* API - fourteen digit american petroleum institue number

* API10 - ten digit american petroleum institue number. Represents a unique hole in the ground.

* oper_alias - standardized operator (company) names

* Form_Avg - geological formation names

* PerfLL - wellbore lateral length

* FirstProd - date of first oil/gas production

* Oil_PkNorm_PerK_6mo - peak oil production within the first 6 months of first production, normalized to 1000 ft

# FracFocus Registry data

* pKey - Key index for the table

* JobStartDate - The date on which the hydraulic fracturing job was initiated.  Does not include site preparation or setup.

* JobEndDate - The date on which the hydraulic fracturing job was completed.  Does not include site teardown.

* APINumber - The American Petroleum Institute well identification number formatted as follows xx-xxx-xxxxx0000 Where: First two digits 
represent the state, second three digits represent the county, third 5 digits represent the well.

* StateNumber - The first two digits of the API number.  Range is from 01-50.

* CountyNumber - The 3 digit county code.

* OperatorName - The name of the operator.

* WellName - The name of the well.

* Latitude - The lines that circle the earth horizontally, running side to side at equal distances apart on the earth.   Latitude is typically 
expressed in degrees North/ South.  In the FracFocus system these lines are shown in decimal degrees and must be between 15 and 75.

* Longitude - The lines that circle the earth vertically, running top to bottom that are equal distances apart at the equator 
and merge at the geographic top and bottom of the earth.  Longitude is typically expressed in degrees East/ West.  In the FracFocus 
system the number representing these  lines are shown in decimal degrees and must be between -180 and -163 Note: Longitude number must 
be preceded by a negative sign.

* Projection - The geographic coordinate system to which the latitude and longitude are related. In the 
* FracFocus 
system the projection systems allowed are NAD (North American Datum) 27 or 83 and UTM (Universal Transverse Mercator).

* TVD - The vertical distance from a point in the well (usually the current or final depth) to a point at the surface, usually the 
elevation of the rotary kelly bushing.

* TotalBaseWaterVolume - The total volume of water used as a carrier fluid for the hydraulic fracturing job (in gallons).

* TotalBaseNonWaterVolume - The total volume of non water components used as a carrier fluid for the hydraulic fracturing job (in gallons)

* StateName - The name of the state where the surface location of the well resides.  Calculated from the API number.

* CountyName - The name of the county were the surface location of the well resides.  Calculated from the API number.

* FFVersion - A key which designates which version of FracFocus was used when the disclosure was submitted.

* FederalWell - True = Yes, False = No.

# R Packages Used

* tidyverse

* magrittr

* kableExtra

* car

# Data Sets Created to Tidy Data

* ff_distinct_api <- fracfocus %>% 
  distinct(api)
  
Create new data set to find distinct observations by api number

* wells_distinct_api14 <- driftwood %>%
    inner_join(fracfocus, by = c("api", "api")) %>%
    distinct(api)
Create new data set to combine well data with fracturing chemical data for further analysis

* ff_summary <- fracfocus %>%
    filter('sand' %in% ingredientname
        | 'silica' %in% ingredientname
        | 'propp' %in% ingredientname
        | 'mesh' %in% ingredientname
        | 'brown' %in% ingredientname
        | 'white' %in% ingredientname
        | '30%50' %in% ingredientname
        | '40%70' %in% ingredientname
        | '30%50' %in% ingredientname
        | '100' %in% ingredientname
        ) %>%
    group_by(api10) %>%
    summarize(totalwater = max(totalbasewatervolume)
              , totalsand = sum(massingredient)
              , percenthfjob = sum(percenthfjob)
              )

Create new data set to aggregate sand and water based on specific wells


