---
title: "Exploratory Data Analysis"
date: "July 30, 2018"
output:
  html_document:
    df_print: kable
    toc: yes
---




# Setup

```{r setup, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(echo = TRUE)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(plot.title = ggplot2::element_text(hjust = 0.5))
knitr::opts_chunk$set(fig.width=6,#12, 
                      fig.height=4,#8, 
                      fig.path='Figs/',
                      warning=FALSE, 
                      message=FALSE)

require(tidyverse)
require(magrittr)
require(kableExtra)
require(car)
options(knitr.table.format = "asis")#"markdown")

setwd("C:/Repositories/DDS_Case_Study_2")

#prevent implicit conversion to scientific notation
options(scipen = 999)


cool_1 = "steelblue"

```


# Function Definitions

```{r}
summarize_frame <- function(dataframe)
{
    #returns table of summary statistics for each numberic column in dataframe
    as.data.frame(summarytools::descr(dataframe, transpose = TRUE)) %>%
    rownames_to_column('attribute') %>%
    mutate_if(is.numeric, round) %>%
    column_to_rownames('attribute') %>%
    select(Mean, Median, Min, Max, Std.Dev, Q1, Q3, IQR, N.Valid, Pct.Valid) 


}


    #as.data.frame(summarytools::descr(ff_summary, transpose = TRUE)) %>%
    #rownames_to_column('attribute') %>%
    #mutate_if(is.numeric, round) %>%
    #column_to_rownames('attribute') %>%
    #select(Mean, Median, Min, Max, Std.Dev, Q1, Q3, IQR, N.Valid, Pct.Valid)

```


# Import Data

```{r}

getwd()

fracfocus <- read.csv("data/fracfocus_registry.csv") %>%
              rename(API = 'APINumber') %>%
              mutate(API = as.character(API)
                     , API10 = as.character(API10)
                     , JobStartDate = as.Date(JobStartDate, "%m/%d/%Y")
                     , JobEndDate = as.Date(JobEndDate, "%m/%d/%Y")
                     , TotalBaseWaterVolume = as.double(TotalBaseWaterVolume)
                     , TotalBaseNonWaterVolume = as.double(TotalBaseNonWaterVolume)
                     , PercentHighAdditive = as.double(PercentHighAdditive)
                     , PercentHFJob = as.double(PercentHFJob)
                     , MassIngredient = as.double(MassIngredient)
                     , IsWater = as.logical.factor(IsWater)
                     ) %>%
                     select(API
                     , API10
                     , WellName
                     , OperatorName
                     , JobStartDate
                     , JobEndDate
                     , Latitude
                     , Longitude
                     , TotalBaseWaterVolume
                     , TotalBaseNonWaterVolume
                     , StateName
                     , CountyName
                     , IngredientName
                     , PercentHighAdditive
                     , PercentHFJob
                     , MassIngredient
                     , IsWater
                     )


driftwood <- read.csv("data/deo_well_data.csv") %>%
              rename(API = 'ï..API') %>%
              mutate(API = as.character(API)
                     , API10 = as.character(API10)
                     , PerfLL = as.integer(PerfLL)
                     , FirstProd = as.Date(FirstProd, "%m/%d/%Y")
                     , Oil = as.integer(Oil_PkNorm_Perk_6mo) #Oil_PkNorm_Perk_6mo
                     , FirstProd_Year = as.integer(format(FirstProd, '%Y'))
                     ) %>%
                     select(-Oil_PkNorm_Perk_6mo)









```



# Supplementary Data Frames - Unique record per well

```{r}

ff_distinct_api <- fracfocus %>%
    distinct(API)

wells_distinct_api14 <- driftwood %>%
    inner_join(fracfocus, by = c("API", "API")) %>%
    distinct(API)

wells_distinct_api10 <- driftwood %>%
    inner_join(fracfocus, by = c("API10", "API10")) %>%
    distinct(API10)



```

# Clean Frac Focus Data

### Frac Focus Summary - Unique record per well

```{r}
ff_summary <- fracfocus %>%
    filter('sand' %in% IngredientName
        | 'silica' %in% IngredientName
        | 'propp' %in% IngredientName
        | 'mesh' %in% IngredientName
        | 'brown' %in% IngredientName
        | 'white' %in% IngredientName
        | '30%50' %in% IngredientName
        | '40%70' %in% IngredientName
        | '30%50' %in% IngredientName
        | '100' %in% IngredientName
        ) %>%
        group_by(API10) %>%
        summarize(TotalWater = max(TotalBaseWaterVolume)
              , TotalSand = sum(MassIngredient)
              , PercentHFJob = sum(PercentHFJob)
# Add additional summary variables here.
              )


ff_summary %>% head()

summarize_frame(ff_summary)

```




















































