---
title: "Exploratory Data Analysis"
date: "July 24, 2018"
output:
  html_document:
    df_print: kable
    toc: yes
---

# Setup

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(plot.title = ggplot2::element_text(hjust = 0.5))
knitr::opts_chunk$set(fig.width=12, 
                      fig.height=8, 
                      fig.path='Figs/',
                      warning=FALSE, 
                      message=FALSE)

require(tidyverse)
require(magrittr)
require(kableExtra)
options(knitr.table.format = "markdown")

setwd("C:/Repositories/DDS_Case_Study_2")

#prevent implicit conversion to scientific notation
options(scipen = 999)


```


# Import Datasets

```{r}

getwd()

fracfocus <- read.csv("data/fracfocus_registry.csv") %>%
              rename(API='APINumber') %>%
              mutate( API=as.character(API)
                     ,API10 = as.character(API10)
                     ,JobStartDate=as.Date(JobStartDate, "%m/%d/%Y")
                     ,JobEndDate=as.Date(JobEndDate, "%m/%d/%Y")
                     ,TotalBaseWaterVolume = as.double(TotalBaseWaterVolume)
                     ,TotalBaseNonWaterVolume = as.double(TotalBaseNonWaterVolume)
                     ,PercentHighAdditive = as.double(PercentHighAdditive)
                     ,PercentHFJob = as.double(PercentHFJob)
                     ,MassIngredient = as.double(MassIngredient)
                     ,IsWater = as.logical.factor(IsWater)
                     ) %>%
              select( API
                     ,API10
                     ,WellName
                     ,OperatorName
                     ,JobStartDate
                     ,JobEndDate
                     ,Latitude
                     ,Longitude
                     ,TotalBaseWaterVolume
                     ,TotalBaseNonWaterVolume
                     ,StateName
                     ,CountyName
                     ,IngredientName
                     ,PercentHighAdditive
                     ,PercentHFJob
                     ,MassIngredient
                     ,IsWater
                     )


driftwood <- read.csv("data/deo_well_data.csv") %>%
              rename(API = 'ï..API') %>%
              mutate(API = as.character(API)
                     , API10 = as.character(API10)
                     ,PerfLL=as.integer(PerfLL)
                     , FirstProd = as.Date(FirstProd, "%m/%d/%Y")
                     ,Oil_PkNorm_Perk_6mo = as.integer(Oil_PkNorm_Perk_6mo)
                     )


```

```{r}

ff_distinct_api <- fracfocus %>%
    distinct(API)



wells_distinct_api14 <- driftwood %>%
    inner_join(fracfocus, by = c("API", "API")) %>%
    distinct(API)

wells_distinct_api10 <- driftwood %>%
    inner_join(fracfocus, by = c("API10", "API10")) %>%
    distinct(API10)

```




```{r}

# Aggregate sand and water
#-- 20/40, 40/70, 30/50, 100 Mesh


# Latitude = Important
# Longitude = Important
# Form_Avg = Very Important
# Sand = Very Important
# Water = Very Important
# Other chemicals / additives = ???


ff_summary <- fracfocus %>%
    filter('sand' %in% IngredientName
        | 'silica' %in% IngredientName
        | 'propp' %in% IngredientName
        | 'mesh' %in% IngredientName
        | 'brown' %in% IngredientName
        | 'white' %in% IngredientName
        | '30%50' %in% IngredientName
        | '40%70' %in% IngredientName
        | '30%50' %in% IngredientName
        | '100' %in% IngredientName
        ) %>%
    group_by(API10) %>%
    summarize(TotalWater = max(TotalBaseWaterVolume)
              , TotalSand = sum(MassIngredient)
              , PercentHFJob = sum(PercentHFJob)
              # Add additional summary variables here.
              )


ff_summary %>% head()

```



```{r}

well_data <- driftwood %>%
    inner_join(ff_summary, by = c("API10", "API10")) %>%
    mutate(lb_ft = TotalSand / PerfLL
           , bbl_ft = TotalWater / PerfLL
           , gal_ft = bbl_ft / 42
           )



well_data %>% head()

```


##### Additive concentrations vs productivity




##### Avg Frac Size by Year


```{r}


ggplot((styles %>% drop_na(ibu)), aes(x = "", y = ibu)) +
      geom_point(aes(fill = ifelse((ibu %in% ibu_outliers), "Outlier", "Valid")),
                 size = 4,
                 shape = 21,
                 position = position_jitter()) +
                 stat_boxplot(geom = 'errorbar') +
                 geom_boxplot(alpha = .5,
                   outlier.shape = NA) +
                   guides(fill = guide_legend(title = NULL))


```



##### Pk-6mo-oil by year


##### Is PkNorm_6mo_Oil normally distributed for each formation?


