---
title: "Measuring Well Productivity by Completion Design"
author: | 
        | Flaming  
        | Trevathan
        | Nixon  
        | Friedrich
output:
  prettydoc::html_pretty:
    keep_md: yes
    theme: leonids
    highlight: github
    toc: true
    number_sections: true
    df_print: kable
    fontsize: 11pt
    fontfamily: palatino

date: "July 24, 2018"

---

<!-- ```{r code = readLines('Setup.R'), message=FALSE, warning=FALSE} -->
<!-- ``` -->

```{r setup, echo=FALSE, results="hide"}
# run setup files, create custom functions, and read in data for analysis
source("Setup.R")
source("Functions.R")
read_chunk('DataImport-FracFocus.R')
read_chunk('DataImport-WellFeatures.R')
read_chunk('Explore_Data.R')

```


# Executive Summary




# Frac Focus Data


## Import

```{r fracfocus_import, cache = TRUE}
```

## Count Locations and Wellbores

```{r fracfocus_count, cache = TRUE}
```

## Aggregate Proppant and Water by wellbore

```{r fracfocus_summary, cache = TRUE}
```

## Aggregates

```{r fracfocus_aggregates, cache = TRUE}
```

# Well Features and Characteristics

```{r wellfeatures_import, cache = TRUE}
```

## Count Locations and Wellbores

```{r wellfeatures_count, cache = TRUE}
```

## Aggregates

```{r fracfocus_aggregates, cache = TRUE}
```



# Data Exploration

## Add Calculated Columns

```{r exp_welldata_calcs}
```

## Clean data

```{r exp_welldata_calcs}
```

## Summarize Well Data 

```{r exp_summary}
```

```{r exp_boxplot_fracsize}
```

```{r exp_boxplot_fracsize}
```


### Frequencies

```{r exp_freq_vintage}
```


```{r exp_freq_status}
```



# Appendix:

```{r}
sessionInfo()
```